cargo-features = ["edition2024"]

[package]
name = "firmaware"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.9.0"
actix-files = "0.6.6"
serde = {version = "1.0.210", features = ["derive"]}

handlebars = {version = "6.1.0", features = ["dir_source"]}
